
package com.company.productappfrontend.ui;

import com.company.productappfrontend.HasTitle;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "", layout = MainLayout.class)
public class HomeView extends VerticalLayout implements HasTitle
{
	public HomeView()
	{
		super();
		this.initUI();
	}

	@Override
	public String getTitle()
	{
		return "Home";
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.paragraph = new Paragraph();
		
		this.paragraph.setText("This is the Homeview!");
		
		this.paragraph.setWidthFull();
		this.paragraph.setHeight(null);
		this.add(this.paragraph);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private Paragraph paragraph;
	// </generated-code>

}
