
package com.company.productappfrontend.ui;

import java.io.ByteArrayInputStream;

import com.company.productappfrontend.domain.Product;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Image;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.server.StreamResource;


public class ViewProductDetails extends HorizontalLayout
{
	
	/**
	 *
	 */
	public ViewProductDetails()
	{
		super();
		this.initUI();
	}
	
	public void setProduct(final Product product)
	{
		if(product.getImageName() != null)
		{
			StreamResource streamResource = null;
			try
			{
				streamResource =
					new StreamResource(product.getImageName(),
						() -> new ByteArrayInputStream(product.getImageBytes()));
			}
			catch(final NullPointerException npe)
			{
				npe.printStackTrace();
			}
			
			final Image newImage = new Image(streamResource, "Productimage");
			newImage.setHeight("350px");
			newImage.setWidth("350px");
			this.div.removeAll();
			this.add(newImage);
		}
		else
		{
			this.div.removeAll();
		}
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.div   = new Div();
		this.image = new Image();
		
		this.image.setWidth("350px");
		this.image.setHeight("350px");
		this.div.add(this.image);
		this.div.setSizeUndefined();
		this.add(this.div);
		this.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.div);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Image image;
	private Div   div;
	// </generated-code>
	
}
